build:
    stage: build
    image:
        name: ubuntu:latest
    script:
        - apt update
        - apt install -y curl
        - curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.38.0/install.sh | bash
        - echo $HOME
        - source $HOME/.bashrc
        - nvm install 14
        - npm i -g @electron-forge/cli
        - npm i
        - make dist
