build:
    stage: build
    image:
        name: ubuntu:latest
    script:
        - curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.38.0/install.sh | bash
        - nvm install 14
        - nvm use 14
        - npm i -g @electron-forge/cli
        - npm i
        - make dist
