image: ubuntu:latest

.build_base:
    before_script:
        - apt update
        - export TZ="America/Toronto"
        - ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
        - apt install -y curl make git wine mono-devel fakeroot zip rpm
        - dpkg --add-architecture i386
        - apt update
        - apt install -y wine32
        - curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.38.0/install.sh | bash
        - export NVM_DIR="$HOME/.nvm"
        - \. "$NVM_DIR/nvm.sh"
        - nvm install 14
        - npm i -g --unsafe-perm @electron-forge/cli
        - npm i --unsafe-perm
        - export VERSION=$(node -p "require('./package.json').version")

build:win64:
    extends: .build_base
    script:
        - which electron-forge
        - make win64
        - electron-forge make --targets="@electron-forge/maker-squirrel" --platform="win32" --arch="x64"
        - $HOME/.nvm/versions/node/v14.17.0/bin/electron-forge make --targets="@electron-forge/maker-squirrel" --platform="win32" --arch="x64"
        - ll out/make/
    # artifacts:
    #     name: epic-dashboard-$VERSION-$CI_COMMIT_SHORT_SHA.exe
    #     paths:
    #         - 'out/make/**/*.exe'
    #     expire_in: 2 mos

# build:win32:
#     extends: .build_base
#     after_script:
#         - make win32
#         - mv out/make/squirrel.windows/ia32/* ./
#     artifacts:
#         name: epic-dashboard-$VERSION-$CI_COMMIT_SHORT_SHA.exe
#         paths:
#             - 'out/make/**/*.exe'
#         expire_in: 2 mos

# build:deb32:
#     extends: build_base
# build:deb64:
#     extends: build_base
# build:debarmhf:
#     extends: build_base
# build:debarm64:
#     extends: build_base
# build:rpm32:
#     extends: build_base
# build:rpm64:
#     extends: build_base
# build:mac:
#     extends: build_base

    # extends: build_base
    # stage: build
    # image:
    #     name: ubuntu:latest
    # script:
    #     - make dist
    #     - export VERSION=$(node -p "require('./package.json').version")
    # artifacts:
    #     paths:
    #         - '**/*.deb'
    #         - '**/*.exe'
    #         - '**/*.zip'
    #     expire_in: 2 mos
