build:
    stage: build
    image:
        name: ubuntu:latest
    script:
        - apt update
        - apt install -y curl
        - curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.38.0/install.sh | bash
        - export NVM_DIR="$HOME/.nvm"
        - \. "$NVM_DIR/nvm.sh"
        - nvm install 14
        - sudo npm i -g @electron-forge/cli
        - sudo npm i
        - make dist
