build:
    stage: build
    image:
        name: ubuntu:latest
    script:
        - apt update
        - export TZ="America/Toronto"
        - ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
        - apt install -y curl make git wine mono-devel fakeroot zip rpmbuild
        - dpkg --add-architecture i386
        - apt update
        - apt install -y wine32
        - curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.38.0/install.sh | bash
        - export NVM_DIR="$HOME/.nvm"
        - \. "$NVM_DIR/nvm.sh"
        - nvm install 14
        - npm i -g --unsafe-perm @electron-forge/cli
        - npm i --unsafe-perm
        - make dist
        - mv out/make/* ./
        - export VERSION=$(node -p "require('./package.json').version")
    artifacts:
        paths:
            - '**/*.deb'
            - '**/*.exe'
            - '**/*.zip'
        expire_in: 2 mos
