image: ubuntu:latest

.build_base:
    before_script:
        - apt update
        - export TZ="America/Toronto"
        - ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
        - apt install -y curl make git wine mono-devel fakeroot zip rpm
        - dpkg --add-architecture i386
        - apt update
        - apt install -y wine32
        - curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.38.0/install.sh | bash
        - export NVM_DIR="$HOME/.nvm"
        - \. "$NVM_DIR/nvm.sh"
        - nvm install 14
        - npm i -g --unsafe-perm @electron-forge/cli
        - npm i --unsafe-perm
        - export VERSION=$(node -p "require('./package.json').version")

build:win64:
    extends: .build_base
    script:
        - make win64
    artifacts:
        name: epic-dashboard-$VERSION-$CI_COMMIT_SHORT_SHA.exe
        paths:
            - 'out/make/**/*.exe'
        expire_in: 2 mos

build:win32:
    extends: .build_base
    after_script:
        - make win32
    artifacts:
        name: epic-dashboard-$VERSION-$CI_COMMIT_SHORT_SHA.exe
        paths:
            - 'out/make/**/*.exe'
        expire_in: 2 mos

build:deb32:
    extends: .build_base
    after_script:
        - make deb32
    artifacts:
        name: epic-dashboard-$VERSION-$CI_COMMIT_SHORT_SHA.deb
        paths:
            - 'out/make/**/*.deb'
        expire_in: 2 mos

build:deb64:
    extends: .build_base
    after_script:
        - make deb64
    artifacts:
        name: epic-dashboard-$VERSION-$CI_COMMIT_SHORT_SHA.deb
        paths:
            - 'out/make/**/*.deb'
        expire_in: 2 mos

build:debarmhf:
    extends: .build_base
    after_script:
        - make debarmhf
    artifacts:
        name: epic-dashboard-$VERSION-$CI_COMMIT_SHORT_SHA.deb
        paths:
            - 'out/make/**/*.deb'
        expire_in: 2 mos

build:debarm64:
    extends: .build_base
    after_script:
        - make debarm64
    artifacts:
        name: epic-dashboard-$VERSION-$CI_COMMIT_SHORT_SHA.deb
        paths:
            - 'out/make/**/*.deb'
        expire_in: 2 mos

build:rpm32:
    extends: .build_base
    after_script:
        - make rpm32
    artifacts:
        name: epic-dashboard-$VERSION-$CI_COMMIT_SHORT_SHA.rpm
        paths:
            - 'out/make/**/*.rpm'
        expire_in: 2 mos

build:rpm64:
    extends: .build_base
    after_script:
        - make rpm64
    artifacts:
        name: epic-dashboard-$VERSION-$CI_COMMIT_SHORT_SHA.rpm
        paths:
            - 'out/make/**/*.rpm'
        expire_in: 2 mos

build:mac:
    extends: .build_base
    after_script:
        - make mac
    artifacts:
        name: epic-dashboard-mac-$VERSION-$CI_COMMIT_SHORT_SHA.zip
        paths:
            - 'out/make/**/*.zip'
        expire_in: 2 mos