import * as React from 'react';

export class Eula extends React.Component {
    render() {
        return (
            <div style={{ pageBreakInside: 'avoid'}}>
                <h1 id="epic-blockchain-technologies-inc-epic-mining-dashboard-license-agreement">
                    <strong>ePIC Blockchain Technologies Inc. - ePIC Mining Dashboard License Agreement</strong>
                </h1>
                <h5 id="copyright-c-2020-epic-blockchain-technologies-inc">
                    <strong>Copyright (c) 2020 ePIC Blockchain Technologies Inc.</strong>
                </h5>
                <hr />
                <h4 id="please-read-this-end-user-license-agreement-the-agreement-carefully-before-downloading-installing-or-using-epic-mining-dashboard-the-application.by-clicking-i-agreeor-by-downloadingthe-applicationyou-are-indicating-that-you-have-read-and-understand-this-agreement-and-accept-its-terms-and-conditions">
                    <strong>Please read this End-User License Agreement (the "Agreement") carefully before downloading, installing, or using ePIC Mining Dashboard (the "Application").</strong> By clicking “I Agree”or by downloadingthe Application,you are indicating that you have read and understand this Agreement and accept its terms and conditions.</h4>
                <h4 id="this-agreement-is-a-legal-agreement-between-you-either-an-individual-or-a-single-entity-and-epic-blockchain-technologies-inc.and-it-governs-your-use-of-the-application-made-available-to-you-by-epic-blockchain-technologies">
                    <strong>This Agreement is a legal agreement between you (either an individual or a single entity) and ePIC Blockchain Technologies Inc., and it governs your use of the Application made available to you by ePIC Blockchain Technologies.</strong>
                </h4>
                <h4 id="you-expressly-acknowledge-and-agree-that-use-of-the-application-is-at-your-sole-risk-and-that-the-entire-risk-as-to-satisfactory-quality-performance-accuracy-and-effort-is-with-you.to-the-maximum-extent-permitted-by-applicable-law-the-software-is-provided-to-you-as-is-and-as-available-with-all-faults-and-without-warranty-of-any-kind-without-performance-assurances-or-guarantees-of-any-kind.epic-blockchain-technologies-inc.does-not-make-and-hereby-disclaims-any-and-all-express-implied-or-statutory-warranties-including-implied-warranties-of-condition-uninterrupted-use-accuracy-of-data-merchantability-satisfactory-quality-fitness-for-a-particular-purpose-noninfringement-of-third-party-rights-and-warranties-if-any-arising-from-a-course-of-dealing-usage-or-trade-practice.epic-blockchain-technologies-inc.does-not-warrant-against-interference-with-your-enjoyment-of-the-software-that-the-software-will-meet-your-requirements-that-operation-of-the-software-will-be-uninterrupted-or-error-free-or-that-any-errors-in-the-software-will-be-corrected.no-oral-or-written-information-or-advice-given-by-epic-blockchain-technologies-inc.or-epic-blockchain-technologies-inc.s-channel-partners-or-any-authorized-representative-shall-create-a-warranty.should-the-application-prove-defective-you-assume-the-entire-cost-of-all-necessary-servicing-repair-or-correction.some-jurisdictions-do-not-allow-the-exclusion-of-or-limitations-on-implied-warranties-or-the-limitations-on-the-applicable-statutory-rights-of-a-consumer-so-some-or-all-of-the-above-exclusions-and-limitations-apply-only-to-the-fullest-extent-permitted-by-law-in-the-applicable-jurisdiction">
                    <strong>YOU EXPRESSLY ACKNOWLEDGE AND AGREE THAT USE OF THE APPLICATION IS AT YOUR SOLE RISK AND THAT THE ENTIRE RISK AS TO SATISFACTORY QUALITY, PERFORMANCE, ACCURACY AND EFFORT IS WITH YOU. TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, THE SOFTWARE IS PROVIDED TO YOU “AS IS” AND “AS AVAILABLE”, WITH ALL FAULTS AND WITHOUT WARRANTY OF ANY KIND, WITHOUT PERFORMANCE ASSURANCES OR GUARANTEES OF ANY KIND.  EPIC BLOCKCHAIN TECHNOLOGIES INC. DOES NOT MAKE, AND HEREBY DISCLAIMS, ANY AND ALL EXPRESS, IMPLIED OR STATUTORY WARRANTIES, INCLUDING IMPLIED WARRANTIES OF CONDITION, UNINTERRUPTED USE, ACCURACY OF DATA, MERCHANTABILITY, SATISFACTORY QUALITY, FITNESS FOR A PARTICULAR PURPOSE, NONINFRINGEMENT OF THIRD PARTY RIGHTS, AND WARRANTIES (IF ANY) ARISING FROM A COURSE OF DEALING, USAGE, OR TRADE PRACTICE. EPIC BLOCKCHAIN TECHNOLOGIES INC. DOES NOT WARRANT AGAINST INTERFERENCE WITH YOUR ENJOYMENT OF THE SOFTWARE; THAT THE SOFTWARE WILL MEET YOUR REQUIREMENTS; THAT OPERATION OF THE SOFTWARE WILL BE UNINTERRUPTED OR ERROR-FREE, OR THAT ANY ERRORS IN THE SOFTWARE WILL BE CORRECTED. NO ORAL OR WRITTEN INFORMATION OR ADVICE GIVEN BY EPIC BLOCKCHAIN TECHNOLOGIES INC. OR EPIC BLOCKCHAIN TECHNOLOGIES INC.’S CHANNEL PARTNERS OR ANY AUTHORIZED REPRESENTATIVE SHALL CREATE A WARRANTY. SHOULD THE APPLICATION PROVE DEFECTIVE, YOU ASSUME THE ENTIRE COST OF ALL NECESSARY SERVICING, REPAIR OR CORRECTION. SOME JURISDICTIONS DO NOT ALLOW THE EXCLUSION OF OR LIMITATIONS ON IMPLIED WARRANTIES OR THE LIMITATIONS ON THE APPLICABLE STATUTORY RIGHTS OF A CONSUMER, SO SOME OR ALL OF THE ABOVE EXCLUSIONS AND LIMITATIONS APPLY ONLY TO THE FULLEST EXTENT PERMITTED BY LAW IN THE APPLICABLE JURISDICTION.</strong>
                </h4>
                <h4 id="to-the-extent-not-prohibited-by-law-in-no-event-will-epic-blockchain-technologies-inc.or-epic-blockchain-technologies-inc.s-channel-partners-be-liable-for-personal-injury-or-any-incidental-special-indirect-or-consequential-damages-whatsoever-including-without-limitation-damages-for-loss-of-profits-loss-of-data-business-interruption-or-any-other-commercial-damages-or-losses-arising-out-of-or-related-to-your-use-or-inability-to-use-the-application-however-caused-regardless-of-the-theory-of-liability-contract-tort-including-for-negligence-breach-of-statutory-duty-or-otherwise-even-if-forseeable-or-otherwise-and-even-if-epic-blockchain-technologies-inc.or-epic-blockchain-technologies-inc.s-channel-partners-have-been-advised-of-the-possibility-of-such-damages.some-jurisdictions-do-not-allow-the-limitation-of-liability-for-personal-injury-or-of-incidental-or-consequential-damages-so-this-limitation-may-not-apply-to-you">
                    <strong>TO THE EXTENT NOT PROHIBITED BY LAW, IN NO EVENT WILL EPIC BLOCKCHAIN TECHNOLOGIES INC. OR EPIC BLOCKCHAIN TECHNOLOGIES INC.’S CHANNEL PARTNERS BE LIABLE FOR PERSONAL INJURY, OR ANY INCIDENTAL, SPECIAL, INDIRECT OR CONSEQUENTIAL DAMAGES WHATSOEVER, INCLUDING, WITHOUT LIMITATION, DAMAGES FOR LOSS OF PROFITS, LOSS OF DATA, BUSINESS INTERRUPTION OR ANY OTHER COMMERCIAL DAMAGES OR LOSSES, ARISING OUT OF OR RELATED TO YOUR USE OR INABILITY TO USE THE APPLICATION HOWEVER CAUSED, REGARDLESS OF THE THEORY OF LIABILITY (CONTRACT, TORT (INCLUDING FOR NEGLIGENCE), BREACH OF STATUTORY DUTY OR OTHERWISE, EVEN IF FORSEEABLE, OR OTHERWISE) AND EVEN IF EPIC BLOCKCHAIN TECHNOLOGIES INC.  OR EPIC BLOCKCHAIN TECHNOLOGIES INC.’S CHANNEL PARTNERS HAVE BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES. SOME JURISDICTIONS DO NOT ALLOW THE LIMITATION OF LIABILITY FOR PERSONAL INJURY OR OF INCIDENTAL OR CONSEQUENTIAL DAMAGES, SO THIS LIMITATION MAY NOT APPLY TO YOU.</strong>
                </h4>
                <h4 id="epic-blockchain-technologies-inc.reserves-the-right-to-modify-suspend-or-discontinue-temporarily-or-permanently-the-application-or-any-service-to-which-it-connects-with-or-without-notice-and-without-liability-to-you">
                    <strong>ePIC Blockchain Technologies Inc. reserves the right to modify, suspend or discontinue, temporarily or permanently, the Application or any service to which it connects, with or without notice and without liability to you.</strong>
                </h4>
                <h4 id="epic-blockchain-technologies-inc.may-from-time-to-time-provide-enhancements-or-improvements-to-the-featuresfunctionality-of-the-application-which-may-include-patches-bug-fixes-updates-upgrades-and-other-modifications">
                    <strong>ePIC Blockchain Technologies Inc. may from time to time provide enhancements or improvements to the features/functionality of the Application, which may include patches, bug fixes, updates, upgrades and other modifications.</strong>
                </h4>
                <h4 id="epic-blockchain-technologies-inc.may-in-its-sole-discretion-at-any-time-and-for-any-or-no-reason-suspend-or-terminate-this-agreement-with-or-without-prior-notice">
                    <strong>ePIC Blockchain Technologies Inc. may, in its sole discretion, at any time and for any or no reason, suspend or terminate this Agreement with or without prior notice.</strong>
                </h4>
                <h4 id="subject-to-the-terms-of-this-agreement-you-are-granted-a-worldwide-non-exclusive-non-transferrable-non-assignable-terminablelicense-to-use-this-application.all-other-rights-are-reserved.this-license-is-personal-to-youwhether-you-are-an-individual-or-a-single-entity-and-cannot-be-transferred-or-sublicensed.your-license-terminates-immediately-if-you-attempt-to-circumvent-any-technical-protection-measures-used-in-connection-with-the-application-or-you-otherwise-breach-the-terms-of-this-agreement">
                    <strong>Subject to the terms of this Agreement, you are granted a worldwide</strong>, non-exclusive, non-transferrable, non-assignable, terminablelicense to use this Application. All other rights are reserved.  This license is personal to you(whether you are an individual or a single entity), and cannot be transferred or sublicensed. Your license terminates immediately if you attempt to circumvent any technical protection measures used in connection with the Application or you otherwise breach the terms of this Agreement.</h4>
                <h4 id="you-may-use-the-application-for-the-purpose-of-cryptocurrencymining">You may use the Application for the purpose of cryptocurrencymining.</h4>
                <h4 id="you-shall-not-and-shall-not-allow-others-to-modify-make-derivative-works-based-upon-recreate-generate-disassemble-decompile-reverse-engineer-reverse-assemble-reverse-compile-or-otherwise-attempt-to-derive-the-human-readable-form-of-the-source-code-of-any-parts-of-or-the-whole-of-this-application.you-will-not-remove-alter-or-otherwise-tamper-with-any-trade-marks-trade-names-logos-numbers-or-other-means-of-identification-on-any-aspects-of-the-application">
                    <strong>You shall not, and shall not allow others to, modify, make derivative works based upon, recreate, generate, disassemble, decompile, reverse engineer, reverse assemble, reverse compile or otherwise attempt to derive the human-readable form of the source code of any parts of</strong> or the whole of this Application. You will not remove, alter or otherwise tamper with any trade marks, trade names, logos, numbers or other means of identification on any aspects of the Application.</h4>
                <h2 id="privacy">
                    <strong>Privacy</strong>
                </h2>
                <h4 id="by-installing-accessing-or-using-the-application-you-consent-to-these-information-collection-and-usage-terms.you-agree-that-epic-blockchain-technologies-inc.may-collect-and-use-technical-data-and-related-information-including-but-not-limited-to-technical-information-about-your-device-system-and-application-software-and-peripherals-that-is-gathered-periodically-to-facilitate-the-provision-of-software-updates-product-support-and-other-services-to-you-if-any-related-to-the-application.epic-blockchain-technologies-inc.may-use-this-information-as-long-as-it-is-in-a-form-that-does-not-personally-identify-you-to-improve-its-products-or-to-provide-services-or-technologies-to-you">
                    <strong>By installing, accessing or using the Application, you consent to these information collection and usage terms.  You agree that ePIC Blockchain Technologies Inc. may collect and use technical data and related information, including but not limited to technical information about your device, system and application software, and peripherals, that is gathered periodically to facilitate the provision of software updates, product support and other services to you (if any) related to the Application. ePIC Blockchain Technologies Inc. may use this information, as long as it is in a form that does not personally identify you, to improve its products or to provide services or technologies to you.</strong>
                </h4>
                <h4 id="epic-blockchain-technologies-inc.respects-your-privacy-rights-and-recognizes-the-importance-of-protecting-any-information-collected-about-you.epic-blockchain-technologies-inc.s-privacy-policy-as-amended-from-time-to-time-is-available-at-privacy-policy-and-applicable-to-this-agreement.by-installing-accessing-or-using-the-application-you-explicitly-agree-with-the-terms-and-conditions-of-epic-blockchain-technologies-inc.s-privacy-policy-and-to-any-terms-and-conditions-included-therein-by-reference">
                    <strong>ePIC Blockchain Technologies Inc. respects your privacy rights and recognizes the importance of protecting any information collected about you. ePIC Blockchain Technologies Inc.’s privacy policy as amended from time to time is available at ("<a href="https://github.com/EPICBOOST/ePIC-Boost-Miner/blob/master/privacy">Privacy Policy</a>") and applicable to this Agreement. By installing, accessing or using the Application you explicitly agree with the terms and conditions of ePIC Blockchain Technologies Inc.’s Privacy Policy and to any terms and conditions included therein by reference.</strong>
                </h4>
                <h2 id="how-to-contact-us">
                    <strong>How to Contact Us</strong>
                </h2>
                <h4 id="notices-and-questions-concerning-the-application-or-any-aspect-of-this-agreement-may-be-directed-to-epic-blockchain-technologies-inc.by-emailing-us-at-supportepicblockchain.io">Notices and questions concerning the Application or any aspect of this Agreement may be directed to ePIC Blockchain Technologies Inc. by emailing us at support@epicblockchain.io.</h4>
                <h4 id="this-agreement-shall-be-governed-by-the-laws-of-ontario-and-the-laws-of-canada-applicable-therein.the-united-nations-convention-for-the-international-sale-of-goods-shall-not-apply.the-parties-agree-that-any-dispute-related-to-this-agreement-shall-be-brought-in-a-court-located-in-toronto-ontario-which-shall-include-but-not-be-limited-to-the-federal-court-of-canada-sitting-in-toronto-to-whose-jurisdiction-the-parties-hereby-irrevocably-attorn.notwithstanding-this-in-the-event-a-party-wishes-to-seek-injunctive-relief-with-respect-to-any-matter-related-to-this-agreement-either-party-may-seek-such-injunctive-relief-in-a-court-of-competent-jurisdiction">
                    <strong>This agreement shall be governed by the laws of Ontario and the laws of Canada applicable therein.  The United Nations Convention for the International Sale of Goods shall not apply. The parties agree that any dispute related to this agreement shall be brought in a court located in Toronto, Ontario (which shall include but not be limited to the Federal Court of Canada sitting in Toronto), to whose jurisdiction the parties hereby irrevocably attorn.  Notwithstanding this, in the event a Party wishes to seek injunctive relief with respect to any matter related to this Agreement either Party may seek such injunctive relief in a court of competent jurisdiction.</strong>
                </h4>
                <p>TODO attribution</p>
                <p>
                    <strong>
                        <a href="https://github.com/EPICBOOST/ePIC-Boost-Miner/releases">Download</a> TODO. BY DOWNLOADING, INSTALLING, AND/OR USING THIS SOFTWARE, YOU ARE AGREEING TO THE TERMS OF THIS EULA.</strong>
                </p>
            </div>
        );
    }
}