#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo "running pre-commit script ..."
GIT_EMAIL=$(git config --get user.email)

if [ ! -z $(echo $GIT_EMAIL | grep -iPo "epicblockchain.io") ]; then
    echo "running lint and format..."

    npm install
    npm run lint
    npm run format
    git diff --exit-code
else
    echo "Forgot to configure epicblockchain.io email:
    
    git config user.email \"<user>@epicblockchain.io\"
    "
    exit 1
fi
